[tool.poetry]
name = "no-doze"
version = "0.1.0"
description = "Highly customizable service to inhibit a computer from going to sleep"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "no_doze"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.30.0"
pyyaml = "^6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
