general:
  # options INFO or DEBUG
  logging_level: "INFO"

  # Settings you probably don't need to touch. Default values are shown

  # no-doze root directory
  # base_dir: "./"

  # times we should try connecting once we find a server before giving up.
  # max_reconnections: 3

  # Delay before retrying (generally waiting for a response from the server)
  # retry_delay_sec: 1

  # Add a delay to checking any Inhibiting Conditions to allow services to come online on boot.
  # startup_delay_min: 0

plugins:
  # To disable a plugin simply comment it out or delete it

  # Suspend sleep on plex media playback
  plex:
      # Plex server token: see plex documentation
      token: "A1A1A1A1A1A1A1A1A1A1"

      # Url of the server you're trying to connect to
      base_url: "http://localhost:32400"

      # time between checks, how long sleep should be prevented after a positive check
      period_min: 10

      # set to INF to inhibit sleep indefinitely while playback is *paused*, set to 0 never inhibit sleep due to paused playback
      max_periods_paused: 3

  # Suspend sleep on qBittorrent transfers
  qbittorrent:
      # Url to qBittorrent Web UI you would like to monitor
      host_url: "http://localhost:8080"

      # use an empty string ("") for no username
      username: "admin"

      # use an empty string ("") for no password
      password: "123456789"

      # To disable downloading or upload sleep inhibition, delete or comment out the section
      downloading:
          # Time in minutes between checks and how long sleep should be delayed for when the speed threshold is exceeded
          period_min: 10

          # Threshold speed in kB/s that should inhibit sleep.  Speed is the simple average over the period_min
          min_speed_kbps: 10
      seeding:
          period_min: 10
          min_speed_kbps: 25

  # Suspend sleep when a process is running
  active-process:
      # Provide a list of {name, period} corresponding to the processes you would like to monitor
      processes:
            # name of the process as it appears in top or ps
          - name: "make"

            # period between checks of the process and how long sleep should be inhibited after a positive check
            period_min: 10

          - name: "apt"
            period_min: 10
          - name: "emerge"
            period_min: 10

  # Suspend Sleep when sshd is running
  # remove or comment out this key to disable
  sshd:
      # period between checks of the process and how long sleep should be inhibited after a positive check
      period_min: 10
      max_periods: 144 # 1440 min (1 day)
