"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/login1
Bus name   : org.freedesktop.login1
"""

#Truncated to remove unused portions of the interface

from jeepney.wrappers import MessageGenerator, new_method_call


class Manager(MessageGenerator):
    interface = 'org.freedesktop.login1.Manager'

    def __init__(self, object_path='/org/freedesktop/login1',
                 bus_name='org.freedesktop.login1'):
        super().__init__(object_path=object_path, bus_name=bus_name)

    def Inhibit(self, what, who, why, mode):
        return new_method_call(self, 'Inhibit', 'ssss',
                               (what, who, why, mode))